AWSTemplateFormatVersion: '2010-09-09'
Description: Master Root Stack orchestrating CloudShirt AWS Basics infrastructure.

Parameters:
  
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair for SSH administration
    Default: vockey
    
  DBUsername:
    Type: String
    Default: cloudshirtadmin
    NoEcho: true
    
  DBPassword:
    Type: String
    Default: ChangeMe123!
    NoEcho: true

Resources:
    # 1. Base Networking (VPCs, Subnets across AZ A & AZ B, Route Tables)
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./01-networking.yaml

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkingStack
    Properties:
      TemplateURL: ./02-security.yaml
      Parameters:
        VpcId: !GetAtt NetworkingStack.Outputs.VPCRef

  StorageStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkingStack
    Properties:
      TemplateURL: ./03-storage.yaml
      Parameters:
        PublicSubnet1: !GetAtt NetworkingStack.Outputs.PublicSubnet1Ref
        PublicSubnet2: !GetAtt NetworkingStack.Outputs.PublicSubnet2Ref
        EFSSecurityGroupId: !GetAtt SecurityStack.Outputs.EFSSecurityGroupRef

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkingStack
    Properties:
      TemplateURL: ./04-database.yaml
      Parameters:
        PrivateSubnet1: !GetAtt NetworkingStack.Outputs.PrivateSubnet1Ref
        PrivateSubnet2: !GetAtt NetworkingStack.Outputs.PrivateSubnet2Ref
        DBSecurityGroupId: !GetAtt SecurityStack.Outputs.DBSecurityGroupRef
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword

  ApplicationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [NetworkingStack, SecurityStack]
    Properties:
      TemplateURL: ./05-application.yaml
      Parameters:
        VpcId: !GetAtt NetworkingStack.Outputs.VPCRef

  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkingStack
    Properties:
      TemplateURL: ./06-monitoring.yaml
      Parameters:
        VpcId: !GetAtt NetworkingStack.Outputs.VPCRef

  ServerlessStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkingStack
    Properties:
      TemplateURL: ./07-serverless.yaml
      Parameters:
        VpcId: !GetAtt NetworkingStack.Outputs.VPCRef

Outputs:
  NetworkingStackOutput:
    Description: "Networking Stack ID"
    Value: !Ref NetworkingStack

  SecurityStackOutput:
    Description: "Security Stack ID"
    Value: !Ref SecurityStack

  StorageStackOutput:
    Description: "Storage Stack ID"
    Value: !Ref StorageStack

  DatabaseStackOutput:
    Description: "Database Stack ID"
    Value: !Ref DatabaseStack

  ApplicationStackOutput:
    Description: "Application Stack ID"
    Value: !Ref ApplicationStack

  MonitoringStackOutput:
    Description: "Monitoring Stack ID"
    Value: !Ref MonitoringStack

  ServerlessStackOutput:
    Description: "Serverless Stack ID"
    Value: !Ref ServerlessStack